use portable_pty::{CommandBuilder, PtySize, native_pty_system};
use std::io::{Read, Write};
use std::path::{Path, PathBuf};
use std::sync::mpsc;
use std::time::{SystemTime, UNIX_EPOCH};

pub enum PtyInput {
    Data(Vec<u8>),
    Resize { cols: u16, rows: u16 },
    Shutdown,
}

const BUFF_CAPACITY: usize = 16 * 1024;
const DEFAULT_TMUX_SESSION: &str = "memtty";
const DEFAULT_PATH: &str = "/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin";

fn unique_temp_dir(prefix: &str) -> Result<PathBuf, Box<dyn std::error::Error>> {
    let nanos = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .unwrap_or_default()
        .as_nanos();
    let dir = std::env::temp_dir().join(format!("{prefix}-{}-{nanos}", std::process::id()));
    std::fs::create_dir_all(&dir)?;
    Ok(dir)
}

fn basename(path: &str) -> &str {
    Path::new(path)
        .file_name()
        .and_then(|s| s.to_str())
        .unwrap_or(path)
}

fn env_flag_enabled(name: &str) -> bool {
    match std::env::var(name) {
        Ok(value) => matches!(
            value.to_ascii_lowercase().as_str(),
            "1" | "true" | "yes" | "on"
        ),
        Err(_) => false,
    }
}

fn executable_in_path(name: &str) -> Option<String> {
    if name.contains(std::path::MAIN_SEPARATOR) {
        return Path::new(name).is_file().then(|| name.to_string());
    }

    let path = std::env::var_os("PATH")
        .filter(|path| !path.is_empty())
        .unwrap_or_else(|| DEFAULT_PATH.into());
    let mut paths: Vec<PathBuf> = std::env::split_paths(&path).collect();
    paths.extend(std::env::split_paths(DEFAULT_PATH));

    paths
        .into_iter()
        .map(|dir| dir.join(name))
        .find(|path| path.is_file())
        .map(|path| path.to_string_lossy().to_string())
}

fn add_shell_integration(
    cmd: &mut CommandBuilder,
    program_path: &str,
) -> Result<(), Box<dyn std::error::Error>> {
    match basename(program_path) {
        // Zsh doesn't have a simple env var hook like PROMPT_COMMAND, so we
        // provide a tiny ZDOTDIR that chains to the user's real files and then
        // adds preexec/precmd hooks.
        "zsh" => {
            let dir = unique_temp_dir("terminal-zdotdir")?;
            let zshenv_path = dir.join(".zshenv");
            let zshrc_path = dir.join(".zshrc");

            // Note: .zshenv is always sourced; keep it minimal.
            std::fs::write(
                &zshenv_path,
                r#"# Auto-generated by terminal
if [[ -f "$HOME/.zshenv" ]]; then
    source "$HOME/.zshenv"
fi
"#,
            )?;

            std::fs::write(
                &zshrc_path,
                r#"# Auto-generated by terminal
if [[ -f "$HOME/.zshrc" ]]; then
    source "$HOME/.zshrc"
fi

[[ -o interactive ]] || return

__terminal_set_title_pwd() {
    print -nP "\e]2;%~\a"
}

__terminal_set_title_cmd() {
    local cmd="$1"
    cmd="${cmd%% *}"
    [[ -n "$cmd" ]] || return
    print -nP "\e]2;${cmd}\a"
}

__terminal_record_history_cmd() {
    local cmd="$1"
    [[ -n "$cmd" ]] || return
    print -rn -- $'\e]777;history;'"$cmd"$'\a'
}

autoload -Uz add-zsh-hook 2>/dev/null || true
add-zsh-hook precmd __terminal_set_title_pwd
add-zsh-hook preexec __terminal_set_title_cmd
add-zsh-hook preexec __terminal_record_history_cmd
"#,
            )?;

            cmd.env("ZDOTDIR", dir.to_string_lossy().to_string());
            cmd.arg("-l"); // login shell
            cmd.arg("-i"); // interactive
        }

        // For bash we can force a custom rcfile that sources the user's normal
        // bashrc and then appends PROMPT_COMMAND to emit OSC 2.
        "bash" => {
            let dir = unique_temp_dir("terminal-bashrc")?;
            let rc_path = dir.join("bashrc");

            std::fs::write(
                &rc_path,
                r#"# Auto-generated by terminal
if [ -f /etc/bashrc ]; then
    source /etc/bashrc
fi
if [ -f "$HOME/.bashrc" ]; then
    source "$HOME/.bashrc"
fi

__terminal_set_title_pwd() {
    printf '\033]2;%s\007' "$PWD"
}

__terminal_record_history_cmd() {
    local entry cmd
    entry="$(HISTTIMEFORMAT= history 1)"
    if [[ "$entry" =~ ^[[:space:]]*[0-9]+[[:space:]]+(.*)$ ]]; then
        cmd="${BASH_REMATCH[1]}"
        if [[ -n "$cmd" ]]; then
            printf '\033]777;history;%s\007' "$cmd"
        fi
    fi
}

if [ -n "${PROMPT_COMMAND:-}" ]; then
    PROMPT_COMMAND="__terminal_record_history_cmd; __terminal_set_title_pwd; ${PROMPT_COMMAND}"
else
    PROMPT_COMMAND="__terminal_record_history_cmd; __terminal_set_title_pwd"
fi
"#,
            )?;

            cmd.arg("--rcfile");
            cmd.arg(rc_path.to_string_lossy().to_string());
            cmd.arg("--login");
            cmd.arg("-i");
        }
        _ => {}
    }

    Ok(())
}

fn shell_command(shell_path: &str) -> CommandBuilder {
    let mut cmd = CommandBuilder::new(shell_path);

    // Inject shell integration so bash/zsh update tab titles automatically.
    let _ = add_shell_integration(&mut cmd, shell_path);

    cmd
}

fn tmux_command(tmux_path: &str) -> CommandBuilder {
    let session_name =
        std::env::var("TERMINAL_TMUX_SESSION").unwrap_or_else(|_| DEFAULT_TMUX_SESSION.to_string());

    let mut cmd = CommandBuilder::new(tmux_path);
    cmd.arg("new-session");
    cmd.arg("-A");
    cmd.arg("-s");
    cmd.arg(session_name);
    cmd
}

pub fn run(
    tx_ui: mpsc::SyncSender<Vec<u8>>,
    rx_ui: mpsc::Receiver<PtyInput>,
) -> Result<(), Box<dyn std::error::Error>> {
    let pty_system = native_pty_system();
    let pair = pty_system.openpty(PtySize {
        rows: 24,
        cols: 80,
        pixel_width: 1,
        pixel_height: 1,
    })?;

    // Spawn the shell (default to zsh; honor $SHELL when present), optionally
    // attaching to a tmux session when TERMINAL_TMUX is enabled.
    let shell_path = std::env::var("SHELL").unwrap_or_else(|_| "bash".to_string());
    let mut cmd = if env_flag_enabled("TERMINAL_TMUX") {
        if let Some(tmux_path) = executable_in_path("tmux") {
            tmux_command(&tmux_path)
        } else {
            shell_command(&shell_path)
        }
    } else {
        shell_command(&shell_path)
    };

    cmd.env("TERM", "xterm-256color");
    cmd.env("COLORTERM", "truecolor");
    cmd.env("TERM_PROGRAM", "custom-terminal");
    cmd.env("TERM_PROGRAM_VERSION", "0.1.0");
    cmd.env("SHELL", shell_path);
    cmd.env("PATH", DEFAULT_PATH);

    let mut child = pair.slave.spawn_command(cmd)?;

    // We must drop the slave after spawning, or the master read will never EOF
    drop(pair.slave);

    let mut reader = pair.master.try_clone_reader()?;
    let mut writer = pair.master.take_writer()?;
    let master = pair.master;

    // --- Thread: Read from PTY, send to UI ---
    std::thread::spawn(move || {
        let mut read_buf = [0u8; BUFF_CAPACITY];
        loop {
            match reader.read(&mut read_buf) {
                Ok(0) => break,
                Ok(n) => {
                    if tx_ui.send(read_buf[..n].to_vec()).is_err() {
                        break;
                    }
                }
                Err(_) => break,
            }
        }
    });

    while let Ok(input) = rx_ui.recv() {
        match input {
            PtyInput::Data(bytes) => {
                writer.write_all(&bytes)?;
            }
            PtyInput::Resize { cols, rows } => {
                master.resize(PtySize {
                    rows,
                    cols,
                    pixel_width: 1,
                    pixel_height: 1,
                })?;
            }
            PtyInput::Shutdown => {
                break;
            }
        }
    }

    let _ = child.kill();
    let _ = child.wait();

    Ok(())
}
