use portable_pty::{CommandBuilder, PtySize, native_pty_system};
use std::io::{Read, Write};
use std::path::{Path, PathBuf};
use std::time::{SystemTime, UNIX_EPOCH};
use tokio::sync::mpsc;

pub enum PtyInput {
    Data(Vec<u8>),
    Resize { cols: u16, rows: u16 },
    Shutdown,
}

const BUFF_CAPACITY: usize = 1024;

fn unique_temp_dir(prefix: &str) -> Result<PathBuf, Box<dyn std::error::Error>> {
    let nanos = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .unwrap_or_default()
        .as_nanos();
    let dir = std::env::temp_dir().join(format!("{prefix}-{}-{nanos}", std::process::id()));
    std::fs::create_dir_all(&dir)?;
    Ok(dir)
}

fn basename(path: &str) -> &str {
    Path::new(path)
        .file_name()
        .and_then(|s| s.to_str())
        .unwrap_or(path)
}

fn add_shell_integration(
    cmd: &mut CommandBuilder,
    program_path: &str,
) -> Result<(), Box<dyn std::error::Error>> {
    match basename(program_path) {
        // Zsh doesn't have a simple env var hook like PROMPT_COMMAND, so we
        // provide a tiny ZDOTDIR that chains to the user's real files and then
        // adds preexec/precmd hooks.
        "zsh" => {
            let dir = unique_temp_dir("terminal-zdotdir")?;
            let zshenv_path = dir.join(".zshenv");
            let zshrc_path = dir.join(".zshrc");

            // Note: .zshenv is always sourced; keep it minimal.
            std::fs::write(
                &zshenv_path,
                r#"# Auto-generated by terminal
if [[ -f "$HOME/.zshenv" ]]; then
    source "$HOME/.zshenv"
fi
"#,
            )?;

            std::fs::write(
                &zshrc_path,
                r#"# Auto-generated by terminal
if [[ -f "$HOME/.zshrc" ]]; then
    source "$HOME/.zshrc"
fi

[[ -o interactive ]] || return

__terminal_set_title_pwd() {
    print -nP "\e]2;%~\a"
}

__terminal_set_title_cmd() {
    local cmd="$1"
    cmd="${cmd%% *}"
    [[ -n "$cmd" ]] || return
    print -nP "\e]2;${cmd}\a"
}

autoload -Uz add-zsh-hook 2>/dev/null || true
add-zsh-hook precmd __terminal_set_title_pwd
add-zsh-hook preexec __terminal_set_title_cmd
"#,
            )?;

            cmd.env("ZDOTDIR", dir.to_string_lossy().to_string());
            cmd.arg("-i");
        }

        // For bash we can force a custom rcfile that sources the user's normal
        // bashrc and then appends PROMPT_COMMAND to emit OSC 2.
        "bash" => {
            let dir = unique_temp_dir("terminal-bashrc")?;
            let rc_path = dir.join("bashrc");

            std::fs::write(
                &rc_path,
                r#"# Auto-generated by terminal
if [ -f /etc/bashrc ]; then
    source /etc/bashrc
fi
if [ -f "$HOME/.bashrc" ]; then
    source "$HOME/.bashrc"
fi

__terminal_set_title_pwd() {
    printf '\033]2;%s\007' "$PWD"
}

if [ -n "${PROMPT_COMMAND:-}" ]; then
    PROMPT_COMMAND="__terminal_set_title_pwd; ${PROMPT_COMMAND}"
else
    PROMPT_COMMAND="__terminal_set_title_pwd"
fi
"#,
            )?;

            cmd.arg("--rcfile");
            cmd.arg(rc_path.to_string_lossy().to_string());
            cmd.arg("-i");
        }
        _ => {}
    }

    Ok(())
}

pub async fn run(
    tx_ui: mpsc::Sender<Vec<u8>>,
    mut rx_ui: mpsc::UnboundedReceiver<PtyInput>,
) -> Result<(), Box<dyn std::error::Error>> {
    let pty_system = native_pty_system();
    let pair = pty_system.openpty(PtySize {
        rows: 24,
        cols: 80,
        pixel_width: 1,
        pixel_height: 1,
    })?;

    // Spawn the shell (default to zsh; honor $SHELL when present)
    let shell_path = std::env::var("SHELL").unwrap_or_else(|_| "zsh".to_string());
    let mut cmd = CommandBuilder::new(shell_path.clone());
    cmd.env("TERM", "xterm-256color");
    cmd.env("COLORTERM", "truecolor");
    cmd.env("TERM_PROGRAM", "custom-terminal");
    cmd.env("TERM_PROGRAM_VERSION", "0.1.0");

    // Inject shell integration so bash/zsh update tab titles automatically.
    let _ = add_shell_integration(&mut cmd, &shell_path);

    let mut child = pair.slave.spawn_command(cmd)?;

    // We must drop the slave after spawning, or the master read will never EOF
    drop(pair.slave);

    let mut reader = pair.master.try_clone_reader()?;
    let mut writer = pair.master.take_writer()?;
    let master = pair.master;

    // --- Thread: Read from PTY, send to UI ---
    tokio::task::spawn_blocking(move || {
        let mut read_buf = [0u8; BUFF_CAPACITY];
        loop {
            match reader.read(&mut read_buf) {
                Ok(0) => break,
                Ok(n) => {
                    if tx_ui.blocking_send(read_buf[..n].to_vec()).is_err() {
                        break;
                    }
                }
                Err(_) => break,
            }
        }
    });

    while let Some(input) = rx_ui.recv().await {
        match input {
            PtyInput::Data(bytes) => {
                writer.write_all(&bytes)?;
            }
            PtyInput::Resize { cols, rows } => {
                master.resize(PtySize {
                    rows,
                    cols,
                    pixel_width: 1,
                    pixel_height: 1,
                })?;
            }
            PtyInput::Shutdown => {
                break;
            }
        }
    }

    let _ = child.kill();
    let _ = child.wait();

    Ok(())
}
